### ISSUE TITLE
Design DB table for storing one-time-use tokens

### ISSUE THREAD

**Issue by kalevias** [jnick1/MyCollege#17]
An database table for storing one-time-use tokens is needed as per #2. See design specification in [UC4](https://github.com/jnick1/MyCollege/wiki/UC4).

The table to be designed has applications beyond that just in this particular UC, but our first use of it will be in this particular instance. One-time-use tokens provide us with a secure way of sending arbitrary information via an HTTP GET request by storing the GET data in our database, as opposed to in the URL itself.

Deliverable: Database SQL code export containing Structure of a table for storing one-time-use tokens saved to the Google Drive.

**Comment by FlamingFoxNinja** [comment]
https://github.com/jnick1/MyCollege/blob/Dev-Account-Management/.documentation/Database/0.1.0%20-%20DB%20Structure.sql

ta dah

**Comment by kalevias** [comment]
Relevant commit:
https://github.com/jnick1/MyCollege/commit/703f3665e4c488ee192e327702fbaacd2810b6fa
