### ISSUE TITLE
Design home page

### ISSUE THREAD

**Issue by kalevias** [jnick1/MyCollege#22]
A home page is required for the site, as per #3. See design specification in [UC5](https://github.com/jnick1/MyCollege/wiki/UC5).

The home page should allow navigation to all important main pages of the site, and must be named `index.php` for the server to correctly recognize it as a homepage. The design should be responsive, and support standard mobile phones, tablets, and desktop screen sizes.

Deliverable: HTML and CSS code committed to GitHub.

**Comment by NabaShauk** [comment]
Homepage is created.
