### ISSUE TITLE
Design login page

### ISSUE THREAD

**Issue by kalevias** [jnick1/MyCollege#23]
A login page is required for the site, as per #3. See design specification in [UC5](https://github.com/jnick1/MyCollege/wiki/UC5).

The login page must be a self-contained page, and not part of any other page (e.g. in a popup). As an independent page, the chance of code injection is reduced. The design should be responsive, and support standard mobile phones, tablets, and desktop screen sizes.

Deliverable: HTML and CSS code committed to GitHub.

**Comment by NabaShauk** [comment]
Login page is completed.
