### ISSUE TITLE
Add input validation to login page

### ISSUE THREAD

**Issue by kalevias** [jnick1/MyCollege#24]
Input validation is needed on the login page as per #3. See design specification in [UC5](https://github.com/jnick1/MyCollege/wiki/UC5).
Input form design task specified in #23.
Refer to our [Data Standards](https://github.com/jnick1/MyCollege/wiki/Data-Standards) when creating the validation code.

Deliverable: JavaScript code for input validation on login page committed to GitHub.

**Comment by hamzashaukat** [comment]
Fixed with input validation commit
