### ISSUE TITLE
Design college search page

### ISSUE THREAD

**Issue by kalevias** [jnick1/MyCollege#41]
A page to display the search results when users search for colleges is needed as per, #36. See design specification in [UC15](https://github.com/jnick1/MyCollege/wiki/UC15).

The design work for the search page has been split into two tasks: this one, and #42.  For this task, the UI for the page which will hold the search results is required.

Deliverable: HTML and CSS code committed to GitHub.

**Comment by NabaShauk** [comment]
Done.
