### ISSUE TITLE
Design college search results

### ISSUE THREAD

**Issue by kalevias** [jnick1/MyCollege#42]
A page to display the search results when users search for colleges is needed as per, #36. See design specification in [UC15](https://github.com/jnick1/MyCollege/wiki/UC15).

The design work for the search page has been split into two tasks: this one, and #41. For this task, the UI for the search results themselves is required (i.e. once the user has made a search using the UI designed in #41, how will the search results be displayed?).

Deliverable: HTML and CSS code committed to GitHub.

**Comment by NabaShauk** [comment]
done
