### ISSUE TITLE
Design DB table for storing college profiles

### ISSUE THREAD

**Issue by kalevias** [jnick1/MyCollege#43]
Database table needs to be designed to store college information as per #38, #39, and #40. See design specification in [UC17](https://github.com/jnick1/MyCollege/wiki/UC17) and [UC18](https://github.com/jnick1/MyCollege/wiki/UC18).

The database table for storing college profiles needs to have enough information available for users to easily search for the college and its relevant information without too much hassle. Some fields may be calculable from others, and thus do not need to be stored, but can be calculated on the fly in either the back-end or front-end.

Deliverable: Database SQL export containing table(s) for storing college profile info committed to GitHub. The database must also be populated with the information from 5 colleges to begin testing the use case functionality related to this task.

**Comment by FlamingFoxNinja** [comment]
c0f9227 
full commit: c0f92277d42800571e076eb4fe72ede3761bafa1
