### ISSUE TITLE
Design college search page filters

### ISSUE THREAD

**Issue by kalevias** [jnick1/MyCollege#47]
Filters need to be added to the college search page to filter search results when a user searches for a college as per, #37. See design specification in [UC16](https://github.com/jnick1/MyCollege/wiki/UC16).

The filters will need to take into account what type of data can be filtered. Filters should fit on the page without requiring the user to scroll to view them all, or some kind of summary should be provided if the user must scroll.

Deliverable: HTML and CSS code committed to GitHub.

**Comment by NabaShauk** [comment]
Filters on the page with the latest commit.
