### ISSUE TITLE
Design and implement frontend filtered search handling

### ISSUE THREAD

**Issue by kalevias** [jnick1/MyCollege#49]
Front-end code to handle filtered college searching MAY be required as per #37. See design specification in [UC16](https://github.com/jnick1/MyCollege/wiki/UC16).

Depending on the implementation path chosen for #48, front-end code to handle a portion of a search request MAY be required. Do not pursue work on this task until the methodology of handling search requests has been determined.

Deliverable if pursued: JavaScript code for partially handling college search requests committed to GitHub.

**Comment by jnick1** [comment]
Backend search method chosen; closing issue, as it is no longer needed.
