### ISSUE TITLE
Design account creation form

### ISSUE THREAD

**Issue by kalevias** [jnick1/MyCollege#6]
A web form is needed for user account creation as per #1. See the design specification in [UC1](https://github.com/jnick1/MyCollege/wiki/UC1), [UC2](https://github.com/jnick1/MyCollege/wiki/UC2), and [UC3](https://github.com/jnick1/MyCollege/wiki/UC3) for required input fields and optional input fields.

The account creation page must be an individually functional web page, i.e. not a popup on another page.

Deliverable: HTML & CSS code for an account creation page committed to GitHub

**Comment by NabaShauk** [comment]
Account creation form is completed.
