### ISSUE TITLE
Add input validation to account creation form

### ISSUE THREAD

**Issue by kalevias** [jnick1/MyCollege#8]
Input validation must be added to the account creation form as per #1. See the design specification in [UC1](https://github.com/jnick1/MyCollege/wiki/UC1), [UC2](https://github.com/jnick1/MyCollege/wiki/UC2), and [UC3](https://github.com/jnick1/MyCollege/wiki/UC3).
Input form design task specified in #6.
Refer to our [Data Standards](https://github.com/jnick1/MyCollege/wiki/Data-Standards) when creating the validation code.

Deliverable: JavaScript code for input validation on account creation form committed to GitHub.

**Comment by hamzashaukat** [comment]
done.
