### ISSUE TITLE
Design DB table for storing user information

### ISSUE THREAD

**Issue by kalevias** [jnick1/MyCollege#9]
Database table needs to be designed to store user information as per #1. See design specification in [UC1](https://github.com/jnick1/MyCollege/wiki/UC1), [UC2](https://github.com/jnick1/MyCollege/wiki/UC2), and [UC3](https://github.com/jnick1/MyCollege/wiki/UC3) for required input fields and optional input fields.

Keep a scale-able design in mind for future expansion of the DB and its tables.

Deliverable: Database SQL code export containing Structure of a table for storing user data saved to the Google Drive.

**Comment by FlamingFoxNinja** [comment]
https://github.com/jnick1/MyCollege/blob/Dev-Account-Management/.documentation/Database/0.1.0%20-%20DB%20Structure.sql

ta dah

**Comment by kalevias** [comment]
Relevant commit:
https://github.com/jnick1/MyCollege/commit/703f3665e4c488ee192e327702fbaacd2810b6fa
